sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install: travis_retry composer install --no-interaction --prefer-source

script:
  - [ [ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ] || [ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ] ] && vendor/bin/phpcs --standard=phpcs.xml src -s

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
